# 도서 정보 테이블 BOOK 테이블
# 저자 정보 테이블 AUTHOR 테이블
# 각 도서의 날짜 별 판매량 정보를 담은 BOOK_SALES 테이블

# 세 테이블에서 2022년 1월의 도서 판매 데이터를 기준으로
# 저자별, 카테고리별 매출액 (TOTAL_SALES + 판매량 * 판매가)를 구하여 -> A.PRICE : 판매가,C.SALES : 판매량
# 저자ID, 저자명, 카테고리, 매출액 출력
# 저자ID 오름차순, 카테고리 내림차순

WITH TEMP AS (
    SELECT A.BOOK_ID, A.CATEGORY, A.AUTHOR_ID, A.PRICE, B.AUTHOR_NAME, C.SALES
    FROM BOOK A
    JOIN AUTHOR B
    ON A.AUTHOR_ID = B.AUTHOR_ID
    JOIN BOOK_SALES C
    ON A.BOOK_ID = C.BOOK_ID
    WHERE YEAR(C.SALES_DATE) = 2022 AND MONTH(C.SALES_DATE) = 1
)

SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE * SALES) AS TOTAL_SALES
FROM TEMP
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC

