
# 3세대 대장균의 ID를 출력하는 SQL
SELECT C.ID
FROM ECOLI_DATA A
INNER JOIN ECOLI_DATA B ON A.ID = B.PARENT_ID # B가 1세대, A가 2세대
INNER JOIN ECOLI_DATA C ON B.ID = C.PARENT_ID # C가 3세대, B가 2세대
WHERE A.PARENT_ID IS NULL
ORDER BY ID ASC