SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN DATE('2022-8-1') AND DATE('2022-10-31') AND
    CAR_ID IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
               WHERE START_DATE BETWEEN DATE('2022-8-1') AND DATE('2022-10-31')
              GROUP BY CAR_ID 
              HAVING COUNT(CAR_ID) >= 5)
GROUP BY MONTH, CAR_ID
HAVING RECORDS >= 1
ORDER BY MONTH, CAR_ID DESC