# 대여 중인 자동차들의 정보를 담은 CAR_RENTAL_COMPANY_CAR 테이블
# 대여 기록 정보 담은 CAR_RENTAL_COMPANY_RENTAL_HISTORY 테이블
# 자동차 종류별 대여 기간 종류별 할인 정책 정보 담은 CAR_RENTAL_COMPANY_DISCOUNT_PLAN 테이블

# 세 테이블에서 자동차 종류가 '세단' 또는 'SUV'인 자동차 중 
# 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능하고
# 30일 간의 대여 금액이 50만원 200만원 미만인 자동차에 대해서
# 자동차ID, 자동차 종류, 대여 금액 출력
# 결과는 대여 금액 기준 내림차순, 자동차 종류 오름차순, 자동차ID 기준 내림차순

WITH TEMP AS (
    SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    WHERE C.CAR_TYPE IN ("SUV", "세단") AND
    C.CAR_ID NOT IN (
        SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= DATE("2022-11-30") AND
        END_DATE >= DATE("2022-11-01")
    )
),
CAR_TABLE AS (
    SELECT A.CAR_ID, A.CAR_TYPE, (
        CASE
        WHEN A.CAR_TYPE = "세단" THEN A.DAILY_FEE * 30 * (100-B.DISCOUNT_RATE) / 100
        WHEN A.CAR_TYPE = "SUV" THEN A.DAILY_FEE * 30 * (100-B.DISCOUNT_RATE) / 100
        END
    ) AS FEE
    FROM TEMP A
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
    ON A.CAR_TYPE = B.CAR_TYPE
    WHERE B.DURATION_TYPE LIKE "30%"
)

SELECT A.CAR_ID, A.CAR_TYPE, FLOOR(FEE) AS FEE
FROM TEMP A
JOIN CAR_TABLE B
ON A.CAR_ID = B.CAR_ID
WHERE B.FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC