WITH AVAILABLE_CARS AS (
    SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    WHERE C.CAR_TYPE IN ('SUV', '세단') 
    AND C.CAR_ID NOT IN (
        SELECT CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )
),
DISCOUNTED_CARS AS (
    SELECT 
        A.CAR_ID, 
        A.CAR_TYPE, 
        FLOOR(A.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE) / 100) AS FEE
    FROM AVAILABLE_CARS A
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
        ON A.CAR_TYPE = D.CAR_TYPE
    WHERE D.DURATION_TYPE = '30일 이상'
)
SELECT CAR_ID, CAR_TYPE, FEE
FROM DISCOUNTED_CARS
WHERE FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;