# 자동차 대여 회사에서 대여 중인 자동차들의 정보를 담은 CAR_RENTAL_COMPANY_CAR 테이블
# 자동차 대여 기록 정보를 담은 CAR_RENTAL_COMPANY_RENTAL_HISTORY 테이블
# 자동차 종류 별 대여 기간 종류 별 할인 정책 CAR_RENTAL_COMPANY_DISCOUNT_PLAN 테이블

# 세 테이블에서 자동차 종류가 세단 또는 SUV인 자동차 중
# 2022년 11월 1일부터 11월 30일까지 대여 가능하고
# 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차에 대해서 
# 자동차 ID, 자동차 종류, 대여 금액 출력
# 대여금액 기준 내림차순, 자동차 종류 오름차순, 자동차ID 기준 내림차순

WITH TEMP AS (
    SELECT A.CAR_ID, A.CAR_TYPE,A.DAILY_FEE, A.OPTIONS
    FROM CAR_RENTAL_COMPANY_CAR A
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    ON A.CAR_ID = B.CAR_ID
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
    ON A.CAR_TYPE = C.CAR_TYPE
    WHERE A.CAR_TYPE IN ('세단', 'SUV') AND
    A.CAR_ID NOT IN (
        SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE START_DATE <= DATE("2022-11-30") AND END_DATE >= DATE("2022-11-01")
    )
),
CAR_TABLE AS (
    SELECT A.CAR_ID, A.DAILY_FEE, A.CAR_TYPE,  B.DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_CAR A
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
    ON A.CAR_TYPE = B.CAR_TYPE
    WHERE B.DURATION_TYPE LIKE "30%"
)

# SELECT * FROM CAR_TABLE

SELECT A.CAR_ID, A.CAR_TYPE, FLOOR(B.DAILY_FEE * (100 - B.DISCOUNT_RATE) / 100 * 30) AS FEE
FROM TEMP A
JOIN CAR_TABLE B
ON A.CAR_ID = B.CAR_ID
WHERE B.DAILY_FEE * (100 - B.DISCOUNT_RATE) / 100 * 30 BETWEEN 500000 AND 1999999
GROUP BY A.CAR_ID, A.CAR_TYPE
ORDER BY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC