SET @HOUR := -1;
SELECT (@HOUR := @HOUR + 1) AS HOUR, 
IFNULL((SELECT COUNT(HOUR(DATETIME))  FROM ANIMAL_OUTS 
 WHERE HOUR(DATETIME) = @HOUR
 GROUP BY HOUR(DATETIME)), 0)
FROM ANIMAL_OUTS
WHERE @HOUR < 23