SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM REST_INFO A
WHERE (A.FOOD_TYPE, A.FAVORITES) IN (
    SELECT FOOD_TYPE, MAX(FAVORITES) FROM REST_INFO B
    GROUP BY FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC