# REST_INFO : 식당 정보 담은 테이블
# 음식 종류별로 즐겨찾기가 가장 많은 식당의
# 음식 종류, ID, 식당 이름, 즐겨찾기 수 조회하는 SQL
# 음식 종류 기준 내림차순
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
    SELECT REST_ID, REST_NAME, FOOD_TYPE, VIEWS, FAVORITES
        ,ROW_NUMBER() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RANKS
    FROM REST_INFO
) AS TEMP
WHERE RANKS = 1
ORDER BY FOOD_TYPE DESC
