SELECT A.MEMBER_NAME, B.REVIEW_TEXT,
    DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d')
FROM MEMBER_PROFILE A
JOIN REST_REVIEW B
ON A.MEMBER_ID = B.MEMBER_ID
WHERE B.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
   GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) DESC
    LIMIT 0,1
                  )
GROUP BY A.MEMBER_NAME, B.REVIEW_TEXT
ORDER BY B.REVIEW_DATE ASC, B.REVIEW_TEXT ASC