# 식품 정보 FOOD_PRODUCT, 식품 주문 정보 FOOD_ORDER
# PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE : FOOD_PRODUCT 테이블
# 식품ID,     식품 이름,       식품 코드,    , 식품분류,  식품 가격
# ORDER_ID, PRODUCT_ID, AMOUNT, PRODUCT_DATE, IN_DATE, OUT_DATE, FACTORY_ID, WAREHOUSE_ID
# 주문ID,   제품ID,     주문량,    생산일자,       입고일자,    출고일자,   공장ID,    창고ID

SELECT A.PRODUCT_ID, A.PRODUCT_NAME,SUM(A.PRICE * B.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT A
JOIN FOOD_ORDER B
ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE B.PRODUCE_DATE BETWEEN DATE("2022-05-01") AND DATE("2022-05-31")
GROUP BY A.PRODUCT_ID, A.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC