# 식품의 정보 담은 FOOD_PRODUCT 테이블
# 식품의 주문 정보 담은 FOOD_ORDER 테이블

# 두 테이블에서 생산일자(FOOD_ORDER.PRODUCE_DATE)가 2022년 5월인 식품들의
# 식품id, 식품 이름, 총 매출을 조회
# 총매출을 기준으로 내림차순 정렬, 식품ID 기준 오름차순

SELECT A.PRODUCT_ID, A.PRODUCT_NAME, SUM(A.PRICE * B.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT A
JOIN FOOD_ORDER B
ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE B.PRODUCE_DATE BETWEEN DATE("2022-05-01") AND DATE("2022-05-31")
GROUP BY A.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC