# 식품의 정보 담은 FOOD_PRODUCT 테이블
# 식품의 주문 정보를 담은 FOOD_ORDER 테이블

# 두 테이블에서 생산일자가 2022년 5월인 식품들의
# 식품ID, 식품 이름, 총 매출을 조회하기
# 결과는 총매출 기준 내림차순, 식품 ID 기준 오름차순

WITH TEMP AS (
    SELECT A.PRODUCT_ID, A.PRODUCT_NAME, A.PRICE, B.AMOUNT
    FROM FOOD_PRODUCT A
    JOIN FOOD_ORDER B
    ON A.PRODUCT_ID = B.PRODUCT_ID
    WHERE YEAR(B.PRODUCE_DATE) = 2022 AND MONTH(B.PRODUCE_DATE) = 5
)

SELECT PRODUCT_ID, PRODUCT_NAME, SUM(PRICE * AMOUNT) AS TOTAL_SALES
FROM TEMP
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC