# 중고거래 게시판 정보 USED_GOODS_BOARD 테이블
# 중고거래 게시판 사용자 정보 USED_GOODS_USER 테이블

# 두 테이블에서 완료된 중고거래의 -> 거래 상태 확인
# 총금액이 70만원 이상인 사람의 -> GROUP BY 하고 SUM
# 회원ID, 닉네임, 총거래금액 조회
# 총거래금액 오름차순

SELECT B.USER_ID, B.NICKNAME, SUM(A.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD A
JOIN USED_GOODS_USER B
ON A.WRITER_ID = B.USER_ID
WHERE A.STATUS = "DONE"
GROUP BY B.USER_ID
HAVING SUM(A.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC

