# 고객 정보를 담은 MEMBER_PROFILE 테이블
# 식당 리뷰 정보를 담은 REST_REVIEW 테이블

# 두 테이블에서 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회
# 회원 이름, 리뷰 텍스트, 리뷰 작성일 출력
# 리뷰 작성일(REVIEW_DATE) 기준 오름차순, 리뷰 텍스트(REVIEW_TEXT) 기준 오름차순

WITH TEMP AS (
    SELECT A.MEMBER_ID
    FROM MEMBER_PROFILE A
    JOIN REST_REVIEW B
    ON A.MEMBER_ID = B.MEMBER_ID 
    GROUP BY A.MEMBER_ID 
    ORDER BY COUNT(*) DESC
    LIMIT 1
),
TT AS (
    SELECT A.MEMBER_ID, A.MEMBER_NAME, B.REVIEW_TEXT, B.REVIEW_DATE
    FROM MEMBER_PROFILE A
    JOIN REST_REVIEW B
    ON A.MEMBER_ID = B.MEMBER_ID
)

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM TT
WHERE MEMBER_ID = (
    SELECT MEMBER_ID FROM TEMP
)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC

