# 아이템 업그레이드
# ITEM_A -> ITEM_B -> ITEM_C
# ITEM_C의 PARENT : ITEM_B
# ITEM_B의 PARENT : ITEM_A
# ROOT : ITEM_A

# 아이템 정보 담은 ITEM_INFO 테이블
# 아이템 관계 나타낸 ITEM_TREE 테이블

# 아이템의 희귀도가 "RARE"인 아이템들의
# 모든 다음 업그레이드 아이템의 
# 아이템ID, 아이템명, 아이템 희귀도 출력 
WITH TEMP AS (
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = "RARE"
)

SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO A
JOIN ITEM_TREE B
ON A.ITEM_ID = B.ITEM_ID
WHERE B.PARENT_ITEM_ID IN (
    SELECT ITEM_ID FROM TEMP
)
ORDER BY A.ITEM_ID DESC