SELECT B.APNT_NO, A.PT_NAME, A.PT_NO, C.MCDP_CD, C.DR_NAME, B.APNT_YMD
FROM PATIENT A
LEFT JOIN APPOINTMENT B
ON A.PT_NO = B.PT_NO
LEFT JOIN DOCTOR C
ON B.MDDR_ID = C.DR_ID
WHERE DATE(B.APNT_YMD) = DATE('2022-4-13') AND B.APNT_CNCL_YN = 'N' AND B.MCDP_CD = 'CS'
ORDER BY B.APNT_YMD