SELECT A.CATEGORY, SUM(B.SALES) AS TOTAL_SALES
FROM BOOK A
JOIN BOOK_SALES B
ON A.BOOK_ID = B.BOOK_ID
WHERE B.SALES_DATE BETWEEN DATE("2022-01-01") AND DATE("2022-01-31")
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY ASC