-- 코드를 입력하세요
-- REST_ID로 조인
SELECT a.REST_ID, a.REST_NAME, a.FOOD_TYPE, a.FAVORITES, a.ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO a
JOIN REST_REVIEW b
ON a.REST_ID = b.REST_ID
WHERE a.ADDRESS LIKE '서울%'
GROUP BY a.REST_ID
ORDER BY ROUND(AVG(REVIEW_SCORE),2) DESC, a.FAVORITES DESC