# 도서 정보 BOOK
#  BOOK_ID, CATEGORY, AUTHOR_ID, PRICE, PUBLISHED_DATE
# 도서ID,  카테고리,   저자 ID,     판매가,   출판일

# 도서의 저자 정보 테이블 AUTHOR
# AUTHOR_ID : 저자 ID, #AUTHOR_NAME : 저자명

# 경제 카테고리에 속하는 도서들의 BOOK_ID, AUTHOR_NAME, PUBLISHED_DATE
# 출판일 기준 오름차순 정렬해서 출력

SELECT A.BOOK_ID, B.AUTHOR_NAME, DATE_FORMAT(A.PUBLISHED_DATE, "%Y-%m-%d")
FROM BOOK A
JOIN AUTHOR B
ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE A.CATEGORY = "경제"
ORDER BY A.PUBLISHED_DATE